// ProfileApplication/ProfileSPA/src/app/profile-register/profile-register.component.ts
import { ProfileService } from '../profile.service';
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { Profile } from '../profile';

@Component({
  selector: 'app-profile-register',
  templateUrl: './profile-register.component.html',
  styleUrls: ['./profile-register.component.css']
})
export class ProfileRegisterComponent implements OnInit {

  profile: Profile = {
    id: 0,
    userId: null,
    userPrincipalName: null,
    givenName: null,
    surname: null,
    jobTitle: null,
    mobilePhone: null,
    preferredLanguage: null,
    firstLogin: true,
  };

  constructor(private router: Router, private service: ProfileService) { }

  ngOnInit(): void {
  }

  confirmRegister(): void {
    console.log(this.profile);
    this.service.postProfile(this.profile).subscribe((response: Profile) => {
      console.log(response);
      this.router.navigate(['/profile-edit', response.id]);
    });
  }
}

<br>
<h3>Welcome Onboard!</h3>
<hr>
<p>You will now be asked to update your profile information.</p>
<button mat-raised-button (click)="confirmRegister()">Accept</button>

// ProfileSPA/src/components/profile/profileRegister/ProfileRegister.jsx
import React, { PureComponent } from 'react';

import {
    Button,
} from 'react-bootstrap';

import './ProfileRegister.css'

class ProfileRegister extends PureComponent {

    handleRegister = () => {
        this.props.postProfile(this.props.profile);
    }

    render() {
        return (
            <div className="p-register">
                <h3>Welcome Onboard!</h3>
                <p>You will now be asked to update your profile information.</p>
                <Button variant="primary" onClick={this.handleRegister}>Accept</Button>
            </div>
        );
    }
}

export default ProfileRegister;
